FROM golang:1.22

WORKDIR /app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod .
COPY go.sum .
COPY main.go .

RUN go mod tidy
RUN go build -o bin .

ENTRYPOINT ["/app/bin"]